version: 0.2

phases:
  install:
    commands:
      - echo Installing install mode...
      - apt install unzip -y
      - wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
      - unzip terraform_1.0.5_linux_amd64.zip
      - sudo mv terraform /usr/local/bin    
  pre_build:
    commands:
      - echo Terraform init...
      - terraform init
      
  build:
    commands:
      - echo Build started on 'date'
      - terraform $TF_COMMAND --auto-approve
      
  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on 'date'
     

