phases:
  install:
    commands:
        - echo "Install apply build"
    pre-build:
      commands:
        - echo "Pre build apply build"
    build:
      commands:
        - echo "Post apply build"
    post_build:
      commands:
         - echo "Post build apply build"
